microlly/urls.py
from django.contrib import admin
from django.conf.urls import url
from microlly_app import views as microlly_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', microlly_views.index, name ='index'),
    path('', include('microlly_app.urls')),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

microlly_app/urls.py
from django.urls import path, include
from django.conf.urls import url
from microlly_app import views

app_name = 'microlly_app'
urlpatterns = [
    #path('', views.index, name ='index'),
    url(r'^$', views.index, name='index'),
    #url(r'^signup/$', views.view_signup, name='signup'),
    #url(r'^login/$', views.view_login, name='login'),
    #url(r'^login/$', views.view_login, {'templates': 'login.html'}, name='login'),
    #url(r'^logout/$', views.view_logout, name='logout'),
    #url(r'^logout/$', views.view_logout, {'next_page': '/'}, name='logout')
    path('signup/', views.view_signup, name='signup'),
    path('login/', views.view_login, name='login'),
    path('logout/', views.view_logout, name='logout'),
    path('create/', views.creationPost, name='create'),
    path('list/', views.postList, name="list"),
    path('UserPost/<str:author>', views.UserPost, name='UserPost'),
    path('post/<slug:slug>/<int:pk>', views.detailsPost, name = 'details'),
    path('edit/<slug:slug>/<int:pk>', views.editPost, name='edit'),
    path('delete/<slug:slug>/<int:pk>', views.deletePost, name='delete'),
]

microlly_app/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify

# Create your models here.

class Publication(models.Model):
    title = models.CharField(max_length=150)
    body = models.CharField(max_length=1000)
    slug = models.SlugField(default='a-slug')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    creation_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now_add=True)


    def preview(self):
        return self.body[:100]+'...'

    def _get_unique_slug(self):
        slug = slugify(self.title)
        unique_slug = slug
        num = 1
        while Publication.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num += 1
        return unique_slug

    def save(self, *args, **kwargs):
        self.slug = self._get_unique_slug()
        super().save(*args, **kwargs)

    class Meta:

        verbose_name='Publication'
        verbose_name_plural='Publications'
    def  __str__(self): # retourne nom afficher pour une publication
        return self.title

microlly_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from microlly_app import models

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(label='Prenom',max_length=30, required=False, help_text='Optionelle.')
    last_name = forms.CharField(label='Nom',max_length=30, required=False, help_text='Optionelle.')
    email = forms.EmailField(max_length=254, required=True,)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

class CustomAuthenticationForm(AuthenticationForm):
    def confirm_login_allowed(self, user):
        if not user.is_active or not user.is_validated:
            raise forms.ValidationError('Probleme d identifiant.', code='invalid_login')


class PostCreate(forms.ModelForm):
        class Meta:
            model = models.Publication
            fields = ['title', 'body']

class PostEdit(forms.ModelForm):
        class Meta:
            model = models.Publication
            fields = ['title', 'body']

microlly_app/views.py
from microlly_app.models import Publication
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.shortcuts import render, redirect, get_object_or_404
from microlly_app import forms
from microlly_app.forms import SignUpForm

# Create your views here.

def index(request):
    publications = Publication.objects.all()
    return render(request, 'index.html', {'latests_publications': publications})

def view_signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('microlly_app:index')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})

def view_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('microlly_app:index')
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})


def view_logout(request):
        logout(request)
        return redirect('microlly_app:index')

#//////////////////////////////////////////



def detailsPost (request, slug, pk):
    post = get_object_or_404(Publication, slug=slug, pk=pk)
    return render(request, 'details.html', {'post':post})

@login_required(login_url = "login/")
def creationPost(request):
    if request.method == 'POST':
        form = forms.PostCreate(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('microlly_app:index')
    else:
        form = forms.PostCreate()
    return render(request, 'creationPost.html', {'form':form})

@login_required(login_url = "login/")
def editPost(request, slug, pk):
    post = get_object_or_404(Publication, slug=slug, pk=pk)
    form = forms.PostEdit(request.POST or None, instance=post)
    if request.user != post.author:
        return redirect('microlly_app:index')
    if request.method =='POST':
        if form.is_valid():
            post.save()
            return redirect('microlly_app:index')
    context = {
        "form":form,
        "post":post,
    }
    return render(request, 'editPost.html', context)


def deletePost (request, slug, pk):
    post = get_object_or_404(Publication, pk=pk)
    if request.user != post.author:
        return redirect('microlly_app:index')
        #return PermissionDenied
    if request.method == 'POST':
        post.delete()
        return redirect('microlly_app:index')

def postList(request):
    posts = Publication.objects.all().order_by('creation_date')
    return render(request, 'list.html', { 'posts': posts })


def UserPost(request, author):
        publication_list = Publication.objects.filter(author=author)
        publication = paginator.get_page(page)
        return render(request, 'UserPost.html', context)
        redirect('microlly_app:index')

microlly_app/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Microlly'Blog{% endblock %}</title>
  </head>
  <body>
    <div class="page-header">

      <h1>Microlly Blog</h1>
      <hr>
    </div>
    <main>
      {% block content %}
      {% endblock %}
    </main>

  </body>
</html>

microlly_app/templates/creationPost.html
{% extends 'base.html' %}

{% block section-title %}
Create a post
{% endblock %}

{% block content %}
    <form class="" action="{% url 'microlly_app:create' %}" method="POST">
        {% csrf_token %}
        {% include 'form.html' with form=form %}
        <input type="submit" value="Create">
    </form>
{% endblock %}

microlly_app/templates/details.html
{% extends 'base.html' %}

{% block section-title %}
Details
{% endblock %}

{% block content %}
<h4>{{ post.title }}</h4>
<p>{{ post.body }}</p>
<p>Created: {{ post.creation_date }}</p>
<p>Edited: {{ post.update_date }}</p>

{% if user.is_authenticated %}
<div class="content">
    <form class="" action="{% url 'microlly_app:delete' post.slug post.pk %}" method="POST">
        {% csrf_token %}
        <button type="submit" type="submit">Delete</button>
    </form>
    <form class="" action="{% url 'microlly_app:edit' post.slug post.pk %}">
        {% csrf_token %}
        <button type="submit" type="submit">Edit</button>
    </form>
</div>
{% endif %}

{% endblock %}

microlly_app/templates/editPost.html
{% extends 'base.html' %}

{% block section-title %}
Edit a post
{% endblock %}

{% block content %}
    <form action="{% url 'microlly_app:edit' post.slug post.pk %}" method="POST">
        {% csrf_token %}
        {% include 'form.html' with form=form %}
        <input type="submit"  value="Edit">
    </form>
{% endblock %}

microlly_app/templates/index.html
{% extends 'base.html' %}

{% block content %}
  {% if user.is_authenticated %}
  Hi {{ user.username }}!
  <a href="{% url 'microlly_app:logout' %}">Se deconnecter</a>
  </br><button><a href="{% url 'microlly_app:create' %}">Ajouter un post</a></button>

  {% else %}
  <p>Vous n'etes pas connecté</p>
  <a href="{% url 'microlly_app:login' %}">Se connecter</a>
  <a href="{% url 'microlly_app:signup' %}">S'inscrire</a>
{% endif %}
<hr>

{% if latests_publications %}

    {% for post in latests_publications %}

            <div class="post">
                <h1>
                    <a  href="{% url 'microlly_app:details' post.slug post.pk %}">{{ post.title }}</a>
                </h1>
                <p class="content">
                    {{post.preview}}
                </p>
            </div>
            <div class="content">
                <p class="content">
                    <small class="content">
                        Posted by: {{post.author}} <!--<a href="{% url 'microlly_app:UserPost' post.author %}">{{post.author}}</a>-->
                        <span class="content">
                            <!--<form class="" action="{% url 'microlly_app:UserPost' post.author %}" method="POST">
                                {% csrf_token %}
                                <button class="btn btn-link" type="submit">{{post.author}}</button>
                            </form>-->
                        </span>
                        {{post.creation_date}}
                    </small>
                </p>
                <p class="content">
                    <small class="date">
                        Last update: {{post.update_date}}
                    </small>
                </p>
            </div>
            <hr>
    {% endfor %}

{% else %}
<p>Aucunes publications.</p>
{% endif %}
{% endblock %}

microlly_app/templates/list.html
{% extends 'base.html' %}

{% block content%}
{% if posts %}

    {% for post in posts %}
    <div class="content">

                    <a href="{% url 'microlly_app:details' post.slug post.pk %}">{{ post.title }}</a>

                <p class="content">
                    {{post.preview}}
                </p>
            </div>
            <div class="content">
                <p class="content">
                    <small class="content">
                        Posted by: {{post.author}} <!--<a href="{% url 'microlly_app:UserPost' post.author %}">{{post.author}}</a>-->
                        <span class="content">
                            <!--<form class="" action="{% url 'microlly_app:UserPost' post.author %}" method="POST">
                                {% csrf_token %}
                                <button class="btn btn-link" type="submit">{{post.author}}</button>
                            </form>-->
                        </span>
                        {{post.creation_date}}
                    </small>
                </p>
                <p class="content">
                    <small class="content">
                        Last update: {{post.update_date}}
                    </small>
                </p>
          <hr>
    {% endfor %}

{% else %}
<p>Aucunes publications.</p>
{% endif %}
{% endblock %}

microlly_app/templates/login.html
{% extends 'base.html' %}

{% block content %}
  <h2>Connexion</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Se connecter</button>
    <a href="{% url 'microlly_app:signup' %}"> <input type="button" value = "s'inscrire" ></a>
    </br>
    <button><a href="{% url 'microlly_app:index' %}">Acceuil</a></button>


  </form>
  {% endblock %}

microlly_app/templates/signup.html
{% extends 'base.html' %}

{% block content %}
  <h2>Inscription</h2>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}

templates/form.html
{% load widget_tweaks %}

{% for hidden_field in form.hidden_fields %}
{{ hidden_field }}
{% endfor %}

{% if form.non_field_errors %}
<div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
    {{ error }}
    {% endfor %}
</div>
{% endif %}

{% for field in form.visible_fields %}
<div class="form-group">
    {{ field.label_tag }}
    {% if form.is_bound %}
        {% if field.errors %}
            {% render_field field class="form-control is-invalid" %}
            {% for error in field.errors %}
                <div class="invalid-feedback">
                    {{ error }}
                </div>
            {% endfor %}
        {% else %}
            {% render_field field class="form-control is-valid" %}
        {% endif %}
    {% else %}
        {% render_field field class="form-control" %}
    {% endif %}
    {% if field.help_text %}
    <small class="form-text text-muted">{{ field.help_text }}</small>
    {% endif %}
</div>
{% endfor %}